DROP TABLE `DOCTOR` IF EXISTS;
DROP TABLE `PATIENT` IF EXISTS;
DROP TABLE `APPOINTMENT` IF EXISTS;

CREATE TABLE DOCTOR (
id VARCHAR(50)  PRIMARY KEY,
name VARCHAR(50)
);

CREATE TABLE PATIENT (
id VARCHAR(50)  PRIMARY KEY,
name VARCHAR(50),
age INT,
gender VARCHAR(45)
);


CREATE TABLE APPOINTMENT (
id VARCHAR(50)  PRIMARY KEY,
localDateTime DATETIME,
CONSTRAINT doctorId FOREIGN KEY (id) REFERENCES DOCTOR(id),
CONSTRAINT patientId FOREIGN KEY (id) REFERENCES PATIENT(id)
);

